#Custom configurations

defaults: &defaults
  DRS2_TIMEOUT: 5
  DRS2_SERVICE_APPKEY: TESTING
  listview_instance: DRS

development:
  <<: *defaults
  DRS2_SERVICE_BASE_URL: https://drs2-services-dev.hul.harvard.edu:18643
  NRS_RESOLVER_URL: http://nrstest.harvard.edu:10031
  
  # properties related to SSL
  CLIENT_KEYSTORE_PATH: /Users/vac765/Documents/DRS2/LO/drs2keys/dev/drs2client.keystore
  CLIENT_KEYSTORE_PASS: drs2webadminpass
  CLIENT_TRUSTSTORE_PATH: /Users/vac765/Documents/DRS2/LO/drs2keys/dev/drs2client.truststore
  CLIENT_TRUSTSTORE_PASS: drs2clienttrustpass
test:
  <<: *defaults

production:
  <<: *defaults