development:
  adapter: postgresql
  encoding: unicode
  database: hollislinks_development
  pool: 5
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: hollislinks_testing
  pool: 5
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: hollislinks_production
  pool: 5
  username: postgres
  password:
